[package]
name = "oxidian"
version.workspace = true
edition.workspace = true

[dependencies]
oxidian-core         = { workspace = true }
oxidian-gateway      = { workspace = true }
oxidian-http         = { workspace = true }
oxidian-interactions = { workspace = true }
oxidian-voice        = { workspace = true }
tracing              = { workspace = true }
tracing-subscriber   = { workspace = true }
rustls               = { workspace = true }
