[package]
name = "oxidian"
version.workspace = true
edition.workspace = true

[[example]]
name = "ping_bot"
path = "../../examples/ping_bot.rs"

[[example]]
name = "slash_commands"
path = "../../examples/slash_commands.rs"

[[example]]
name = "components_v2"
path = "../../examples/components_v2.rs"

[[example]]
name = "low_level"
path = "../../examples/low_level.rs"

[[example]]
name = "multi_shard"
path = "../../examples/multi_shard.rs"

[dependencies]
oxidian-core         = { workspace = true }
oxidian-gateway      = { workspace = true }
oxidian-http         = { workspace = true }
oxidian-interactions = { workspace = true }
oxidian-voice        = { workspace = true }
tokio                = { workspace = true }
serde_json           = { workspace = true }
tracing              = { workspace = true }
tracing-subscriber   = { workspace = true }
rustls               = { workspace = true }
async-trait          = { workspace = true }
