[workspace]
members = [
    "crates/core",
    "crates/gateway",
    "crates/http",
    "crates/interactions",
    "crates/utils",
    "crates/voice",
    "crates/cache",
    "crates/oxidian",
]
exclude = ["testBot"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Ferriteworks/Oxidian"
homepage = "https://github.com/Ferriteworks/Oxidian"
documentation = "https://docs.rs/oxidian"

[workspace.dependencies]
oxidian-core         = { path = "crates/core",         version = "0.1.0" }
oxidian-gateway      = { path = "crates/gateway",      version = "0.1.0" }
oxidian-http         = { path = "crates/http",         version = "0.1.0" }
oxidian-interactions = { path = "crates/interactions", version = "0.1.0" }
oxidian-utils        = { path = "crates/utils",        version = "0.1.0" }
oxidian-voice        = { path = "crates/voice",        version = "0.1.0" }
oxidian-cache        = { path = "crates/cache",        version = "0.1.0" }

dashmap          = "6"
serde            = { version = "1", features = ["derive"] }
serde_json       = "1"
tokio            = { version = "1", features = ["full"] }
thiserror        = "2"
bitflags         = "2"
futures-util     = "0.3"
tokio-tungstenite = { version = "0.26", features = ["rustls-tls-native-roots"] }
reqwest          = { version = "0.12", features = ["json", "multipart"] }
rustls           = { version = "0.23", features = ["ring"] }
tracing          = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait      = "0.1"
